{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcp-gateway.serviceAccountName" . }}
  labels:
    {{- include "mcp-gateway.labels" . | nindent 4 }}
{{- end }}
